---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: javawebapp
  namespace: default
  labels: 
    app: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: "abhilashnarayan/my-app-2.0"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
  namespace: default
spec:
  selector:
    app: javawebapp
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80