---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: javatomcat-app
  namespace: default
  labels:
    app: javatomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javatomcat-app
  template:
    metadata:
      labels:
        app: javatomcat-app
    spec:
      containers:
      - name: javatomcat-app
        image: "abhilashnarayan/my-app-1.0:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: javatomcat-app
  namespace: default
spec:
  selector:
    app: javatomcat-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
    
